[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add= """
  let g:user_emmet_leader_key='<c-e>'
  let g:user_emmet_settings={
    \ 'variables': {
      \ 'lang': 'ja'
    \ },
    \ 'indentation': '  '
  \ }
"""

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = "colorscheme iceberg"

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = """
  let b:ale_linters={
    \ 'python': ['flake8']
    \}
"""

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = """
  let g:terraform_fmt_on_save = 1
"""

[[plugins]]
repo = 'junegunn/goyo.vim'
